export const caseList = [
  {
    Asunto: "CASO 8484 - RECLAMO",
    Texto:
      "Estimados señores o señoras,<br><br>\n          Quiero preguntarle sobre la cobertura de mi seguro de automóvil. El 26 de Mayo tuve un choque y mi auto\n          resultó dañado, y esto presenta daños en la parte delantera del auto. El parachoques fue destruido. Quisiera\n          saber si el seguro de vehículo que tengo en su empresa cubre esto. Si la respuesta es afirmativa, quisiera\n          información sobre los pasos que debo seguir para activar mi seguro de vehículo.<br><br>\n          Quedo a la espera de su amable respuesta.<br>\n          Atentamente,<br>\n          Vanessa Arteaga Molina",
    Complejo: false,
    TiempoEnvio: 0,
    TiempoSolucion: 0,
    Respuestas: [
      "Vanessa",
      "Arteaga",
      "BXD-017",
      "Plan Regular",
      "01/05/2022",
      2,
      2,
      2,
    ],
    Visible: true,
  },

  {
    Asunto: "CASO 8485 - RECLAMO",
    Texto:
      "Estimados señores o señoras,<br><br>\n          El 5 de junio hice un viaje por carretera hacia el norte, choqué mi automóvil con otro automóvil y se\n          rompieron los parachoques. El choque se produjo de tarde y fue muy fuerte. Mi amigo y yo estábamos en el auto,\n          ambos salimos ilesos. Quisiera saber si el seguro de vehículo que tengo en su empresa cubre este tipo de accidentes.<br><br>\n          Quedo a la espera de su amable respuesta.<br>\n          Atentamente,<br>\n          Astrid Wilson",
    Complejo: true,
    TiempoEnvio: 0,
    TiempoSolucion: 0,
    Respuestas: [
      "Astrid",
      "Wilson",
      "BXD-011",
      "Plan Oro",
      "01/08/2022",
      1,
      1,
      "Maria Perez",
      "ROC - 2211",
      1,
      1,
    ],
    Reporte: "technical_report_7.png",
    Visible: true,
  },

  {
    Asunto: "CASO 8486 - RECLAMO",
    Texto:
      "Estimados señores o señoras,<br><br>\n          Me gustaría que me aconsejaran sobre mi seguro de coche. El 27 de Mayo sufrí el robo de partes de mi auto.\n        El robo fue de la radio y la rueda de repuesto. Esto sucedió en la intersección de la calle Quinta con la \n            Tercera Avenida. Me gustaría saber si el seguro del vehículo que tengo cubre esto. Si la respuesta es sí, \n          por favor hágamelo saber lo antes posible para hacer los arreglos correspondientes.<br><br>\n     Gracias de antemano por su ayuda.<br>\n                 Atentamente<br>\n             Jesus Walker",
    Complejo: false,
    TiempoEnvio: 147,
    TiempoSolucion: 0,
    Respuestas: [
      "Jesus",
      "Walker",
      "BXD-012",
      "Plan Diamante",
      "01/09/2022",
      1,
      1,
      1,
    ],
    Visible: true,
  },

  {
    Asunto: "CASO 8487 - RECLAMO",
    Texto:
      "Estimados señores o señoras,<br><br>\n Quiero preguntar sobre mi seguro de automóvil. El 26 de Mayo, tuve un pequeño accidente en el que resultó\n dañado otro automóvil. En particular, el otro automóvil tiene daños en el parachoques trasero.\n Quisiera saber si el seguro del vehículo que tengo con ustedes cubre esto. Si la respuesta es afirmativa,\n quisiera información sobre los pasos que debo seguir para activar mi seguro de vehículo.<br><br>\n Quedo a la espera de su amable respuesta.\nAtentamente<br>\nMaria Sinfuentes",
    Complejo: false,
    TiempoEnvio: 254,
    TiempoSolucion: 0,
    Respuestas: [
      "Maria",
      "Sinfuentes",
      "BXD-003",
      "Plan Diamante",
      "01/12/2022",
      1,
      1,
      1,
    ],
    Visible: true,
  },

  {
    Asunto: "CASO 8488 - RECLAMO URGENTE",
    Texto:
      "Estimados señores o señoras,<br><br>\nQuiero preguntarle sobre mi seguro de automóvil. Ayer tuve un accidente de coche en el que me fracturé\n el tobillo. Me gustaría saber si el seguro del vehículo puede cubrir mis gastos médicos y \n técnicos. La respuesta a esto es crítica porque si es posible, tal vez pueda ir a una clínica privada.<br><br>\n Quedo a la espera de su amable respuesta.\nAtentamente,<br>\nAlannis Diaz",
    Complejo: false,
    TiempoEnvio: 544,
    TiempoSolucion: 0,
    Respuestas: [
      "Alannis",
      "Diaz",
      "BXD-014",
      "Plan Plata",
      "01/11/2022",
      1,
      2,
      2,
    ],
    Visible: true,
  },

  {
    Asunto: "CASO 8489 - RECLAMO",
    Texto:
      "Estimados señores o señora,<br><br>\n Quiero hacer una pregunta sobre mi seguro de automóvil. La semana pasada, tuve un accidente y se dañó la\n parte delantera de mi automóvil. Precisamente, el paragolpes quedó destrozado. Además de eso,\n causé daños a un automóvil extranjero, donde rayé la ventana delantera y se destruyeron el parachoques y \nla luz delantera. Quisiera saber si el seguro de vehículo que tengo en su empresa cubre este tipo de \n accidentes. Si la respuesta es sí, me gustaría obtener más información al respecto.<br><br>\n Espero su respuesta.\n Atentamente,<br>\n William Rivera",
    Complejo: true,
    TiempoEnvio: 739,
    TiempoSolucion: 0,
    Respuestas: [
      "William",
      "Rivera",
      "BXD-016",
      "Plan Regular",
      "01/08/2022",
      1,
      2,
      "Matheo Morgan",
      "TUH - 1044",
      1,
      2,
    ],
    Reporte: "technical_report_1.png",
    Visible: true,
  },

  {
    Asunto: "CASO 8490 - RECLAMO",
    Texto:
      "Estimados señores o señoras,<br><br>\n El 27 de Mayo conduje a la ciudad vecina con mi novio. Para llegar a esta ciudad, tuve que pasar\n por un camino no autorizado, ya que era la ruta más corta para llegar a mi destino. Como eran\n más de las 10 de la noche, no me di cuenta de que había un letrero que me informaba sobre un camino no autorizado.\n Como resultado, entré en un camino sin terminar y tuve un accidente menor. El auto tenía daños en la parte\n delantera. Quisiera saber si el seguro de vehículo que tengo en su empresa cubre este\n tipo de accidentes. Su respuesta me ayudará a hacer los arreglos correspondientes.<br><br>\nQuedo a la espera de su amable respuesta.\nAtentamente,<br>\nNickole Rojas",
    Complejo: true,
    TiempoEnvio: 1270,
    TiempoSolucion: 0,
    Respuestas: [
      "Nickole",
      "Rojas",
      "BXD-016",
      "Plan Diamante",
      "01/03/2022",
      2,
      1,
      "Merry Valverde",
      "DEA - 2214",
      1,
      2,
    ],
    Reporte: "technical_report_3.png",
    Visible: true,
  },

  {
    Asunto: "CASO 8491 - RECLAMO",
    Texto:
      "Estimados señores o señoras,<br><br>\nAyer en un viaje por carretera hacia el sur, choqué mi automóvil con otro automóvil y \nse rompieron los parachoques. El choque se produjo de noche y fue muy fuerte. Mi amigo y yo estábamos en el \nauto, ambos salimos ilesos. Quisiera saber si el seguro de vehículo que tengo en su empresa cubre este\n tipo de accidentes.<br><br>\n Quedo a la espera de su amable respuesta.\n Atentamente,<br>\nBenny Garcia",
    Complejo: true,
    TiempoEnvio: 1328,
    TiempoSolucion: 0,
    Respuestas: [
      "Benny",
      "Garcia",
      "BXD-020",
      "Plan Regular",
      "01/08/2022",
      1,
      2,
      "Alanis Belevan",
      "MIA-3314",
      1,
      2,
    ],
    Reporte: "technical_report_5.png",
    Visible: true,
  },

  {
    Asunto: "CASO 8492 - RECLAMO URGENTE",
    Texto:
      "Estimados señores o señoras,<br><br>\n Quiero hacer una pregunta sobre mi seguro de automóvil. El 26 de Mayo  tuve un accidente \nautomovilístico en el que se dañó la pintura de mi auto en la puerta del conductor. Es más, me golpeé la \nfrente. Ayer tuve dolor y me he automedicado; sin embargo, el dolor persiste hasta el día de hoy \ny con mayor intensidad. Quisiera saber si puedo ir a un hospital privado cubierto por el seguro de mi vehículo.\n Mi coche también está en el taller mecánico. Es importante para mí si el seguro puede \n cubrir mi tratamiento médico.<br><br>\nQuedo a la espera de su amable respuesta.\nAtentamente,<br>\nPaty Jimenez",
    Complejo: false,
    TiempoEnvio: 1587,
    TiempoSolucion: 0,
    Respuestas: [
      "Paty",
      "Jimenez",
      "BXD-010",
      "Plan Oro",
      "01/07/2022",
      1,
      1,
      1,
    ],
    Visible: true,
  },

  {
    Asunto: "CASO 8493 - RECLAMO URGENTE",
    Texto:
      "Estimados señores o señora,<br><br>\n Quiero hacer una pregunta sobre mi seguro de automóvil. Hace dos días, tuve un grave accidente\n automovilístico, donde sufrí un golpe en el brazo izquierdo. Me comuniqué con usted y enviaron un \n inspector para revisar lo sucedido. El Sr. August Marruecos, que vino a revisar el accidente, me dijo que\n la compañía de seguros trabajará para obtener una compensación por las lesiones y daños a mi vehículo. \n Sin embargo, hasta la fecha no se ha recibido ninguna comunicación por su parte. Quisiera saber si el \n seguro del vehículo que tengo con ustedes cubre esto. Si la respuesta es afirmativa, me gustaría recibir\n información sobre los pasos que debo seguir para utilizar mi seguro de vehículo.<br><br>\n Quedo a la espera de su amable respuesta.\n Atentamente, <br>\n Adrian Molina",
    Complejo: true,
    TiempoEnvio: 1679,
    TiempoSolucion: 0,
    Respuestas: [
      "Adrian",
      "Molina",
      "BXD-001",
      "Plan Oro",
      "01/10/2022",
      1,
      1,
      "Mario Valencia",
      "TAH - 1014",
      1,
      1,
    ],
    Reporte: "technical_report_2.png",
    Visible: true,
  },

  {
    Asunto: "CASO 8494 - RECLAMO",
    Texto:
      "Estimados señores o señoras,<br><br>\n Quiero hacer una pregunta sobre mi seguro de automóvil. El 28 de Mayo noté una falla mecánica \n en el motor del auto, por lo que me gustaría tomar un servicio adicional para la asistencia del \n vehículo. Me gustaría saber si el seguro del vehículo que tengo con ustedes cubre esta avería. Si la respuesta \n es afirmativa, quisiera información sobre los pasos que debo seguir para activar mi seguro de vehículo.<br><br>\n Quedo a la espera de su amable respuesta.\nAtentamente <br>\n Abraham Smith",
    Complejo: false,
    TiempoEnvio: 2392,
    TiempoSolucion: 0,
    Respuestas: [
      "Abraham",
      "Smith",
      " BXD-009",
      "Plan Plata",
      "01/08/2022",
      1,
      2,
      2,
    ],
    Visible: true,
  },

  {
    Asunto: "CASO 8495 - RECLAMO",
    Texto:
      "Estimados señores o señora,<br><br>\n Hace dos días, en un viaje por carretera hacia el sur, choqué mi auto con otro auto y se rompieron los parachoques.\n El choque se produjo de noche y fue muy fuerte. Mi esposo y yo estábamos en el auto,\n ambos salimos ilesos. Quisiera saber si el seguro de vehículo que tengo en su empresa cubre este tipo \n de accidentes. Su respuesta me ayudará a hacer los arreglos necesarios.<br><br>\n Gracias por adelantado por tu respuesta.\n Atentamente, <br>\n Fernanda Santos",
    Complejo: true,
    TiempoEnvio: 2411,
    TiempoSolucion: 0,
    Respuestas: [
      "Fernanda",
      "Santos",
      "BXD-013",
      "Plan Regular",
      "01/10/2022",
      1,
      2,
      "Mario Lezameta",
      "ERW - 1114",
      1,
      2,
    ],
    Reporte: "technical_report_6.png",
    Visible: true,
  },

  {
    Asunto: "CASO 8496 - RECLAMO",
    Texto:
      "Estimados señores o señoras,<br><br>\n Quisiera consultar sobre mi seguro de auto. El 27 de Mayo  participé en una carrera de autos \n que se llevó a cabo para recaudar fondos para niños con discapacidades motoras. Durante esta carrera, \n hubo un accidente colectivo, donde mi auto sufrió daños menores. Quisiera consultar sobre mi \ncobertura con respecto a este evento. Si la respuesta es afirmativa, quisiera información sobre los pasos \n que debo seguir para activar mi seguro de vehículo.<br><br>\nGracias de antemano por su ayuda.\nAtentamente,<br>\n Micaela Harris",
    Complejo: false,
    TiempoEnvio: 2526,
    TiempoSolucion: 0,
    Respuestas: [
      "Micaela",
      "Harris",
      "BXD-008",
      "Plan Regular",
      "01/05/2022",
      2,
      2,
      2,
    ],
    Visible: true,
  },

  {
    Asunto: "CASO 8497 - RECLAMO",
    Texto:
      "Estimados señores o señoras,<br><br>\n Tengo una duda sobre mi seguro de coche. El 26 de Mayo  tuve un accidente automovilístico en el que\n se dañó totalmente la perilla de la puerta de mi automóvil. De acuerdo con el informe del accidente,\n mi automóvil estaba sobrepasando el nivel de velocidad legal, y esta fue la principal causa del choque.\n Quisiera saber si el seguro del vehículo que tengo con ustedes cubre esto. A continuación, \n daré los pasos correspondientes.<br><br>\n Quedo a la espera de su amable respuesta.\nAtentamente,<br>\n Valeria Jimenez",
    Complejo: false,
    TiempoEnvio: 2867,
    TiempoSolucion: 0,
    Respuestas: [
      "Valeria",
      "Jimenez",
      "BXD-006",
      "Plan Diamante",
      "01/03/2022",
      2,
      1,
      2,
    ],
    Visible: true,
  },

  {
    Asunto: "CASO 8498 - RECLAMO",
    Texto:
      "Estimados señores o señora,<br><br>\n Me gustaría preguntarle sobre mi seguro de automóvil. Ayer tuve un accidente automovilístico,\n donde sufrí un golpe en la pierna derecha. Me comuniqué con usted y enviaron un inspector para revisar\n lo sucedido. El Sr. Hels Minde, quien vino a revisar el accidente, me dijo que la compañía de \n seguros trabajará para obtener una compensación por mis lesiones y daños a mi vehículo. Sin embargo,\n hasta la fecha, no he recibido ninguna comunicación de ellos. Quisiera saber si el seguro del vehículo \n que tengo con ustedes cubre esto. Si es así, podría hacer los arreglos necesarios.<br><br>\nQuedo a la espera de su amable respuesta.\nAtentamente,<br>\nPaty Jimenez",
    Complejo: true,
    TiempoEnvio: 3024,
    TiempoSolucion: 0,
    Respuestas: [
      "Paty",
      "Jimenez",
      "BXD-010",
      "Plan Oro",
      "01/07/2022",
      1,
      1,
      "Jeremy Salas",
      "ERI-3024",
      1,
      1,
    ],
    Reporte: "technical_report_4.png",
    Visible: true,
  },
];
